name: Lint

on:
  push:
    branches-ignore:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Install Go dependencies
        run: |
          go mod tidy
          go install honnef.co/go/tools/cmd/staticcheck@latest
          go install github.com/kisielk/errcheck@latest
          go install golang.org/x/lint/golint@latest
          go install github.com/axw/gocov/gocov@latest
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          go install github.com/client9/misspell/cmd/misspell@latest

      - name: Run golint
        run: |
          staticcheck ./...
          go fmt $(go list ./... | grep -v /vendor/)
          go vet $(go list ./... | grep -v /vendor/)
          golint -set_exit_status $(go list ./... | grep -v /vendor/)
          errcheck -ignore 'os:.*,' $(go list ./... | grep -v /vendor/)
          misspell -error .
          gosec ./...

  test:
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Install Go dependencies
        run: |
          go mod tidy

      - name: Test
        run: go test ./...
